arch: NestedUNet
batch_size: 16
dataset: data-science-bowl-2018
deep_supervision: false
early_stopping: -1
epochs: 10
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 96
input_w: 96
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: data-science-bowl-2018_NestedUNet_woDS
nesterov: false
num_classes: 3
num_workers: 4
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
