arch: NestedUNet
batch_size: 16
dataset: data
deep_supervision: false
early_stopping: -1
epochs: 100
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 1661
input_w: 593
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: data_NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 4
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
